"""this script turns a knn eval csv file into a latex table for the report"""

import argparse
import os
import sys

import pandas as pd


def format_row(machine: str, row: pd.Series) -> str:
    return (
        f"    {machine:<12} & "
        f"{row['AUC_all']:.4f} & {row['pAUC']:.4f} & "
        f"{row['AUC_source']:.4f} & {row['AUC_target']:.4f} \\\\"
    )


def main():
    # read knn scores from csv and write a commented latex table block
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-csv", required=True)
    parser.add_argument("--out-tex", default="")
    parser.add_argument(
        "--caption",
        default=(
            "kNN evaluation on the DCASE 2025 Task 2 evaluation dataset "
            "(EAT-LoRA checkpoint step 6000, 10\\% synthetic training mix, 15\\,dB synth SNR)."
        ),
    )
    parser.add_argument("--label", default="tab:knn_dcase_eval")
    parser.add_argument(
        "--machine-order",
        nargs="*",
        default=[],
        help="Optionele vaste volgorde van machines in de tabel.",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input_csv):
        raise FileNotFoundError(args.input_csv)

    df = pd.read_csv(args.input_csv).set_index("machine")
    required = ["AUC_all", "pAUC", "AUC_source", "AUC_target"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise KeyError(f"Ontbrekende kolommen in csv: {missing}")

    if args.machine_order:
        machines = [m for m in args.machine_order if m in df.index]
        extra = [m for m in df.index if m not in machines]
        machines.extend(sorted(extra))
    else:
        machines = list(df.index)

    lines = [
        "% Auto-generated by export_knn_latex_table.py",
        "% \\begin{table}[htbp]",
        "%   \\centering",
        f"%   \\caption{{{args.caption}}}",
        f"%   \\label{{{args.label}}}",
        "%   \\begin{tabular}{lcccc}",
        "%     \\toprule",
        "%     Machine & AUC\\textsubscript{all} & pAUC & AUC\\textsubscript{source} & AUC\\textsubscript{target} \\\\",
        "%     \\midrule",
    ]
    for machine in machines:
        lines.append(format_row(machine, df.loc[machine]))
    lines.extend(
        [
            "%     \\bottomrule",
            "%   \\end{tabular}",
            "% \\end{table}",
        ]
    )

    tex = "\n".join(lines) + "\n"
    out_tex = args.out_tex or os.path.splitext(args.input_csv)[0] + ".tex"
    os.makedirs(os.path.dirname(out_tex) or ".", exist_ok=True)
    with open(out_tex, "w", encoding="utf-8") as f:
        f.write(tex)

    print(tex)
    print(f"Opgeslagen: {out_tex}", file=sys.stderr)


if __name__ == "__main__":
    main()
